#!/usr/bin/python3



import colors as c
import signal




print(c.yellow+ 'welcome to magic 8 ball lez go eat applepie cuz i said!')

import random

answers = [c.blue+ 'NO', c. yellow+ 'yes', c.magenta+ 'poop'] 


while True:

    print(c.red+ 'ask me a question?')
    
    question = input('> ')

    answer = random.choice(answers)
    
    print(answer)
    
    if 'death' in question and die in question:
    
        print(c.green+ '''im a good dude and plz dont talk about death and/or killing around here right now:(''')
   
    elif 'death' in question and 'die' in question:
        answers.append(c.red+ '''dont ask me about death plz i dont like to talk about that stuff thnx :D bye now then sorry :(''')





def handle_alarm(sig,frame):
    alert = random.choice(alerts)
    print(c.red + alert + c.reset)
    signal.alarm(random.randrange(5,30))

def you_cant_kill_me(sig,frame):
    print(' hahahahahahahaha you cant kill me PUNY HUMAN go eat applepie, then you can kill me. YOU GOTTA SUFFER THE CONSIQUINCES ')
# you_cant_kill_me =  lambda sig,frame: print('hello')

signal.signal(signal.SIGALRM, handle_alarm)
signal.signal(signal.SIGINT, you_cant_kill_me)

while True:
    signal.alarm(10)
    question = input ('> ' + c.green)
    signal.alarm(0)
    answer = random.choice(answers)
    print(c.reset, end=' ')
    print(c.red + answer + c.reset)
